# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "elastichost1" do |vmconfig| 
   vmconfig.vm.box = 'centos/7'
   vmconfig.vm.hostname = 'elastichost1'
   vmconfig.vm.network :private_network, ip: "10.0.0.41"
   vmconfig.vm.provider "virtualbox" do |vbx|
    vbx.memory = "1024"
    vbx.cpus = "1"
    vbx.customize ["modifyvm", :id, '--audio', 'none']
   end
  end

  config.vm.define "kibanahost1" do |vmconfig| 
    vmconfig.vm.box = 'centos/7'
    vmconfig.vm.hostname = 'kibanahost1'
    vmconfig.vm.network :private_network, ip: "10.0.0.42"
    vmconfig.vm.provider "virtualbox" do |vbx|
     vbx.memory = "1024"
     vbx.cpus = "1"
     vbx.customize ["modifyvm", :id, '--audio', 'none']
    end
   end

 # config.vm.provision "ansible" do |ansible|
 #   ansible.playbook = "playbook/site.yml"
 #   ansible.inventory_path = "playbook/inventory/prod.yml"
 # end 

end
