---
- name: install Nginx and PHP Packages
  apt: 
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - nginx
    - php-fpm
    - php-mysql

- name: install PHP Extensions
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ php_modules }}"
  notify: Restart php-fpm

- name: create Nginx config for {{ domain_name }}
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/sites-available/{{ domain_name }}
  notify: Restart Nginx

- name: enable {{ domain_name }} site
  file:
     src: /etc/nginx/sites-available/{{ domain_name }}
     dest: /etc/nginx/sites-enabled/{{ domain_name }}
     state: link
  notify: Restart Nginx

- name: disable default Nginx site
  file:
     dest: /etc/nginx/sites-enabled/default
     state: absent
  notify: Restart Nginx

- name: download and unpack latest WordPress
  unarchive:
    src: "https://wordpress.org/latest.tar.gz"
    dest: "/var/www"
    remote_src: yes
    creates: "/var/www/wordpress"

- name: set ownership
  file:
    path: "/var/www/wordpress"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data

- name: set up wp-config
  template:
    src: "templates/wp-config.php.j2"
    dest: "/var/www/wordpress/wp-config.php"

