---

  - hosts: nodes
    become: yes
    become_user: root
    remote_user: vagrant

    tasks:
      - name: Create directory for ssh-keys
        file: state=directory mode=0700 dest=/root/.ssh/

      - name: Installing tools
        yum: name={{ item }} state=present
        with_items:
          - git
          - curl

      - name: Add docker repository
        command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

      - name: Installing docker package
        yum: name={{ item }} state=present
        with_items:
          - docker-ce
          - docker-ce-cli
          - containerd.io

      - name: Enable docker daemon
        systemd:
          name: docker
          state: started
          enabled: yes

      - name: Install docker-compose
        raw: $(curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-`uname -s`-`uname -m` -o /usr/bin/docker-compose && chmod +x /usr/bin/docker-compose)

      - name: Add the current user to docker group
        user: name=vagrant append=yes groups=docker

      - name: Synchronization
        copy:
          src: db/
          dest: "/opt/db/"
          owner: root
          group: root
          mode: 0644

      - name: Pull all images in compose
        command: docker-compose -f /opt/db/docker-compose.yaml pull

      - name: Up all services in compose
        command: docker-compose -f /opt/db/docker-compose.yaml up -d