apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://monitoring.{{ domain_name }}:9090
    basicAuth: false
    isDefault: true
    editable: true