gitlabrunner_installation_script_url: "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh"
gitlab_host: "gitlab"
gitlab_external_url: "http://gitlab.{{ domain_name }}"