---
- name: install packages
  apt:
    name: 
      - nginx
      - letsencrypt
      - python3-certbot-nginx
    state: latest
    update_cache: yes

- name: disable default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: create letsencrypt directory
  file:
    path: /var/www/letsencrypt
    state: directory

- name: generate new certificate
  shell: >
    certbot certonly -n --nginx --test-cert --email '{{ letsencrypt_email }}'
    --agree-tos --no-eff-email -d '{{ domain_name }}, www.{{ domain_name }},
    gitlab.{{ domain_name }},grafana.{{ domain_name }},prometheus.{{ domain_name }},
    alertmanager.{{ domain_name }}'
  args:
    creates: /etc/letsencrypt/live/{{ domain_name }}

- name: install nginx available sites
  template:
    src: templates/nginx-{{ item }}.j2
    dest: /etc/nginx/sites-available/{{ item }}
  with_items: 
    - www
    - gitlab
    - grafana
    - prometheus
    - alertmanager
    - redirect
  notify: Restart nginx

- name: enable Nginx sites
  file:
    src: /etc/nginx/sites-available/{{ item }}
    dest: /etc/nginx/sites-enabled/{{ item }}
    state: link
  with_items: 
    - www
    - gitlab
    - grafana
    - prometheus
    - alertmanager
    - redirect
  notify: Restart nginx